"""update user table

Revision ID: 13624f0cf9e0
Revises: cece0de7b5b1
Create Date: 2023-05-18 00:11:22.799591

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13624f0cf9e0"
down_revision = "cece0de7b5b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
